# -*- coding: utf-8 -*-
#
# Copyright (C) 2025 Cottage Labs.
#
# invenio-aisearch is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Configuration for AI-powered search."""

INVENIO_AISEARCH_BASE_TEMPLATE = "invenio_theme/page.html"
"""Default base template for the AI search page."""

INVENIO_AISEARCH_EMBEDDINGS_FILE = None
"""Path to the embeddings JSON file.

Example: "/path/to/instance/embeddings.json"
This file is generated by the embedding generation task or script.
"""

INVENIO_AISEARCH_API_URL = "https://127.0.0.1:5000/api"
"""InvenioRDM API base URL for fetching records.

Used by background tasks to fetch records for embedding generation.
"""

INVENIO_AISEARCH_SEMANTIC_WEIGHT = 0.7
"""Weight for semantic similarity in hybrid search (0.0-1.0).

Higher values prioritize semantic meaning over metadata matching.
"""

INVENIO_AISEARCH_METADATA_WEIGHT = 0.3
"""Weight for metadata matching in hybrid search (0.0-1.0).

Higher values prioritize exact keyword/metadata matches.
"""

INVENIO_AISEARCH_DEFAULT_LIMIT = 10
"""Default number of search results to return."""

INVENIO_AISEARCH_MAX_LIMIT = 100
"""Maximum number of search results allowed."""
